### ISSUE TITLE
NewsListFragment.showLoadFailMsg NullPointerException

### ISSUE THREAD

**Issue by whiskeyfei** [liuling07/SimpleNews#1]
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: com.lauren.simplenews, PID: 12161
                                                                       java.lang.NullPointerException
                                                                           at com.lauren.simplenews.news.widget.NewsListFragment.showLoadFailMsg(NewsListFragment.java:167)
                                                                           at com.lauren.simplenews.news.presenter.NewsPresenterImpl.onFailure(NewsPresenterImpl.java:83)
                                                                           at com.lauren.simplenews.news.model.NewsModelImpl$1.onFailure(NewsModelImpl.java:37)
                                                                           at com.lauren.simplenews.utils.OkHttpUtils$2.run(OkHttpUtils.java:96)
                                                                           at android.os.Handler.handleCallback(Handler.java:733)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at android.os.Looper.loop(Looper.java:136)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                                           at java.lang.reflect.Method.invokeNative(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:515)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                           at dalvik.system.NativeStart.main(Native Method)

**Comment by tonycheng93** [comment]
Shared element must not be null(图片模块，点击图片，怎个APP会Crash)
12-27 20:50:11.840 28979-28979/com.lauren.simplenews E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: com.lauren.simplenews, PID: 28979
                                                                       java.lang.IllegalArgumentException: Shared element must not be null
                                                                           at android.app.ActivityOptions.makeSceneTransitionAnimation(ActivityOptions.java:475)
                                                                           at android.app.ActivityOptions.makeSceneTransitionAnimation(ActivityOptions.java:431)
                                                                           at android.support.v4.app.ActivityOptionsCompat21.makeSceneTransitionAnimation(ActivityOptionsCompat21.java:31)
                                                                           at android.support.v4.app.ActivityOptionsCompat.makeSceneTransitionAnimation(ActivityOptionsCompat.java:134)
                                                                           at com.lauren.simplenews.images.widget.ImageFragment$1.onItemClick(ImageFragment.java:87)
                                                                           at com.lauren.simplenews.images.ImageAdapter$ItemViewHolder.onClick(ImageAdapter.java:107)
                                                                           at android.view.View.performClick(View.java:4825)
                                                                           at android.view.View$PerformClick.run(View.java:20144)
                                                                           at android.os.Handler.handleCallback(Handler.java:815)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                           at android.os.Looper.loop(Looper.java:179)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5543)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:372)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:956)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:751)

**Comment by liuling07** [comment]
@tonycheng93  已经修复了，谢谢。

**Comment by liuling07** [comment]
@whiskeyfei 我修改了代码，你更新下试下还会不会出现。
